import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import { Search, CornerDownLeft, X, FileText } from 'lucide-react'
import { getT } from '../../i18n/t'
import { search, type Doc } from '../../lib/search'

/**
 * Documentation search — a client-side index, fetched on first use.
 *
 * There is no search server. The whole corpus is a few hundred KB of text and
 * the site is a static build served from nginx, so shipping the index and
 * scoring in the browser removes an entire moving part: no query endpoint to
 * keep up, nothing to rate-limit, and search keeps working on a preview build
 * of `dist/` with no backend at all.
 *
 * The index is `/learn/search/<locale>.json`, generated by
 * `src/pages/learn/search/[locale].json.ts`. It is fetched on the FIRST
 * keystroke rather than at page load, so a reader who never searches pays
 * nothing for this component beyond its own bytes.
 */
export default function DocsSearch({
    locale = 'en',
    className = '',
}: {
    locale?: string
    className?: string
}) {
    const t = getT(locale)

    const [open, setOpen] = useState(false)
    const [query, setQuery] = useState('')
    const [docs, setDocs] = useState<Doc[] | null>(null)
    const [loading, setLoading] = useState(false)
    const [failed, setFailed] = useState(false)
    const [cursor, setCursor] = useState(0)

    const inputRef = useRef<HTMLInputElement>(null)
    const listRef = useRef<HTMLUListElement>(null)

    /*
     * The index URL has to be built for the locale in hand: an `es` reader is on
     * `/es/learn/...`, and a bare `/learn/search/es.json` would be right only by
     * luck of the mount point. Deriving it from the endpoint's own root (which
     * the JSON also echoes back) keeps this correct if `/learn` ever moves.
     */
    const indexUrl = useMemo(() => {
        const prefix = locale && locale !== 'en' ? `/${locale}` : ''
        return `${prefix}/learn/search/${locale || 'en'}.json`
    }, [locale])

    const load = useCallback(async () => {
        if (docs || loading) return

        setLoading(true)
        setFailed(false)

        try {
            const res = await fetch(indexUrl)
            if (!res.ok) throw new Error(String(res.status))
            const json = (await res.json()) as { docs: Doc[] }
            setDocs(json.docs)
        } catch {
            setFailed(true)
        } finally {
            setLoading(false)
        }
    }, [docs, loading, indexUrl])

    // ⌘K / Ctrl+K from anywhere, and `/` when not already typing somewhere.
    useEffect(() => {
        const onKey = (e: KeyboardEvent) => {
            const inField =
                e.target instanceof HTMLElement &&
                (e.target.tagName === 'INPUT' ||
                    e.target.tagName === 'TEXTAREA' ||
                    e.target.isContentEditable)

            if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'k') {
                e.preventDefault()
                setOpen((v) => !v)
                return
            }

            if (e.key === '/' && !inField && !open) {
                e.preventDefault()
                setOpen(true)
            }
        }

        window.addEventListener('keydown', onKey)
        return () => window.removeEventListener('keydown', onKey)
    }, [open])

    useEffect(() => {
        if (!open) return

        void load()
        // The dialog owns the page while it is up; restoring scroll on close is
        // handled by simply removing the class again.
        document.documentElement.classList.add('overflow-hidden')
        const id = window.setTimeout(() => inputRef.current?.focus(), 10)

        return () => {
            document.documentElement.classList.remove('overflow-hidden')
            window.clearTimeout(id)
        }
    }, [open, load])

    const hits = useMemo(
        () => (docs ? search(docs, query) : []),
        [docs, query]
    )

    useEffect(() => setCursor(0), [query])

    const onKeyDown = (e: React.KeyboardEvent) => {
        if (e.key === 'Escape') {
            e.preventDefault()
            setOpen(false)
            return
        }

        if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
            e.preventDefault()
            setCursor((c) => {
                const next = e.key === 'ArrowDown' ? c + 1 : c - 1
                if (hits.length === 0) return 0
                return (next + hits.length) % hits.length
            })
            return
        }

        if (e.key === 'Enter') {
            const hit = hits[cursor]
            if (hit) {
                e.preventDefault()
                window.location.href = hit.doc.href
            }
        }
    }

    // Keep the highlighted row in view as the arrows walk past the fold.
    useEffect(() => {
        const el = listRef.current?.children[cursor] as HTMLElement | undefined
        el?.scrollIntoView({ block: 'nearest' })
    }, [cursor])

    return (
        <>
            <button
                type="button"
                onClick={() => setOpen(true)}
                onMouseEnter={() => void load()}
                className={`group flex w-full items-center gap-2 rounded-lg border border-border bg-surface-secondary px-2.5 py-1.5 text-left text-sm text-muted transition-colors hover:border-accent/40 hover:text-foreground ${className}`}
            >
                <Search className="h-4 w-4 shrink-0" />
                <span className="min-w-0 flex-1 truncate">
                    {t('docs.search.placeholder')}
                </span>
                <kbd className="hidden shrink-0 rounded border border-border bg-surface px-1.5 py-px font-mono text-[0.6875rem] text-muted @xs:inline">
                    {shortcutHint()}
                </kbd>
            </button>

            {/*
                Portalled to <body> for the same reason the docs drawer is:
                <main> is a stacking context (`relative z-20` in Layout.astro),
                so a `fixed` overlay rendered inside it cannot rise above the
                shared <Header/> at `z-40`, whatever z-index it asks for.
            */}
            {open && createPortal(
                <div
                    className="fixed inset-0 z-[100] flex items-start justify-center overflow-y-auto p-4 pt-[10vh]"
                    role="dialog"
                    aria-modal="true"
                    aria-label={t('docs.search.title')}
                >
                    <button
                        type="button"
                        aria-label={t('docs.search.close')}
                        onClick={() => setOpen(false)}
                        className="fixed inset-0 cursor-default bg-black/60 backdrop-blur-sm"
                    />

                    <div className="relative w-full max-w-2xl overflow-hidden rounded-2xl border border-border bg-surface shadow-2xl">
                        <div className="flex items-center gap-2 border-b border-border px-4">
                            <Search className="h-4 w-4 shrink-0 text-muted" />
                            <input
                                ref={inputRef}
                                value={query}
                                onChange={(e) => setQuery(e.target.value)}
                                onKeyDown={onKeyDown}
                                type="search"
                                autoComplete="off"
                                spellCheck={false}
                                placeholder={t('docs.search.placeholder')}
                                aria-label={t('docs.search.placeholder')}
                                className="min-w-0 flex-1 bg-transparent py-3.5 text-foreground outline-none placeholder:text-muted"
                            />
                            <button
                                type="button"
                                onClick={() => setOpen(false)}
                                aria-label={t('docs.search.close')}
                                className="rounded p-1 text-muted transition-colors hover:bg-surface-hover hover:text-foreground"
                            >
                                <X className="h-4 w-4" />
                            </button>
                        </div>

                        <div className="max-h-[60vh] overflow-y-auto">
                            {failed ? (
                                <p className="px-4 py-8 text-center text-sm text-muted">
                                    {t('docs.search.failed')}
                                </p>
                            ) : loading && !docs ? (
                                <p className="px-4 py-8 text-center text-sm text-muted">
                                    {t('docs.search.loading')}
                                </p>
                            ) : query.trim().length === 0 ? (
                                <p className="px-4 py-8 text-center text-sm text-muted">
                                    {t('docs.search.hint')}
                                </p>
                            ) : hits.length === 0 ? (
                                <p className="px-4 py-8 text-center text-sm text-muted">
                                    {t('docs.search.empty', { query })}
                                </p>
                            ) : (
                                <ul ref={listRef} className="p-2">
                                    {hits.map((hit, i) => (
                                        <li key={hit.doc.path}>
                                            <a
                                                href={hit.doc.href}
                                                onMouseEnter={() => setCursor(i)}
                                                className={`block rounded-lg px-3 py-2.5 transition-colors ${
                                                    i === cursor
                                                        ? 'bg-accent/12'
                                                        : 'hover:bg-surface-secondary'
                                                }`}
                                            >
                                                <div className="flex items-center gap-2">
                                                    <FileText className="h-3.5 w-3.5 shrink-0 text-muted" />
                                                    <span className="truncate text-xs text-muted">
                                                        {hit.doc.sectionTitle}
                                                    </span>
                                                </div>
                                                <div className="mt-0.5 font-pjs text-sm font-semibold text-foreground">
                                                    {hit.doc.title}
                                                </div>
                                                <p
                                                    className="mt-0.5 line-clamp-2 text-xs text-muted [&_mark]:bg-transparent [&_mark]:font-semibold [&_mark]:text-accent"
                                                    dangerouslySetInnerHTML={{
                                                        __html: hit.snippet,
                                                    }}
                                                />
                                            </a>
                                        </li>
                                    ))}
                                </ul>
                            )}
                        </div>

                        <div className="flex items-center gap-4 border-t border-border px-4 py-2 text-[0.6875rem] text-muted">
                            <span className="flex items-center gap-1">
                                <CornerDownLeft className="h-3 w-3" />
                                {t('docs.search.keyOpen')}
                            </span>
                            <span>↑↓ {t('docs.search.keyMove')}</span>
                            <span>esc {t('docs.search.keyClose')}</span>
                        </div>
                    </div>
                </div>,
                document.body
            )}
        </>
    )
}

/** ⌘K on Apple keyboards, Ctrl K everywhere else. */
function shortcutHint(): string {
    if (typeof navigator === 'undefined') return 'Ctrl K'
    return /Mac|iPhone|iPad/.test(navigator.platform || navigator.userAgent)
        ? '⌘ K'
        : 'Ctrl K'
}
