import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import { Search, CornerDownLeft, X, FileText } from 'lucide-react'
import { getT } from '../../i18n/t'
import { search, type Doc } from '../../lib/search'
import { queryField, track } from '../../lib/umami'

/**
 * Which mounted instance owns the global keyboard shortcut.
 *
 * `DocsNav` renders TWO `<DocsSearch/>`s and both are always mounted: one in
 * the narrow trigger bar (`@4xl:hidden`) and one in the wide rail
 * (`hidden @4xl:block`). Only one is ever VISIBLE, but CSS hiding a container
 * does not unmount what is inside it — so both were listening on `window` for
 * `/` and ⌘K, both set their own `open`, and both `createPortal`'d a dialog to
 * `<body>`.
 *
 * A portal escapes its hidden ancestor, so the result was two full-screen
 * search dialogs stacked exactly on top of each other, two fetches of the
 * index, and Escape closing both. It looked like one dialog, which is why it
 * survived — it was found by instrumenting the component and seeing
 * `docs_search_open` fire twice for one keypress.
 *
 * A module-level claim rather than a prop: which instance is the visible one
 * depends on a CONTAINER query, and JavaScript here cannot know the answer.
 * It does not need to — the dialog is portalled to `<body>` either way, so it
 * renders identically whichever instance owns it. Clicking is unaffected: only
 * the visible instance's button can be clicked in the first place.
 */
let shortcutOwner: symbol | null = null

/**
 * Documentation search — a client-side index, fetched on first use.
 *
 * There is no search server. The whole corpus is a few hundred KB of text and
 * the site is a static build served from nginx, so shipping the index and
 * scoring in the browser removes an entire moving part: no query endpoint to
 * keep up, nothing to rate-limit, and search keeps working on a preview build
 * of `dist/` with no backend at all.
 *
 * The index is `/learn/search/<locale>.json`, generated by
 * `src/pages/learn/search/[locale].json.ts`. It is fetched on the FIRST
 * keystroke rather than at page load, so a reader who never searches pays
 * nothing for this component beyond its own bytes.
 */
export default function DocsSearch({
    locale = 'en',
    className = '',
}: {
    locale?: string
    className?: string
}) {
    const t = getT(locale)

    const [open, setOpen] = useState(false)
    const [query, setQuery] = useState('')
    const [docs, setDocs] = useState<Doc[] | null>(null)
    const [loading, setLoading] = useState(false)
    const [failed, setFailed] = useState(false)
    const [cursor, setCursor] = useState(0)

    const inputRef = useRef<HTMLInputElement>(null)
    const listRef = useRef<HTMLUListElement>(null)

    /*
     * Analytics bookkeeping, in refs rather than state: none of it renders,
     * and putting it in state would re-run the search on every keystroke for
     * the sake of a counter.
     *
     * `lastQuery` is what stops the debounce filing the same settled query
     * twice when a keystroke lands and is deleted again. `picked` is how
     * `docs_search_abandon` knows the difference between a reader who closed
     * the modal having found something and one who gave up — without it, the
     * two are the same close event.
     */
    const lastQuery = useRef('')
    const picked = useRef(false)
    const searched = useRef(false)

    /*
     * The index URL has to be built for the locale in hand: an `es` reader is on
     * `/es/learn/...`, and a bare `/learn/search/es.json` would be right only by
     * luck of the mount point. Deriving it from the endpoint's own root (which
     * the JSON also echoes back) keeps this correct if `/learn` ever moves.
     */
    const indexUrl = useMemo(() => {
        const prefix = locale && locale !== 'en' ? `/${locale}` : ''
        return `${prefix}/learn/search/${locale || 'en'}.json`
    }, [locale])

    /*
     * Whether this open has already tried to fetch the index.
     *
     * A ref, and load-bearing rather than tidy. The guard used to be
     * `if (docs || loading) return`, and when the fetch FAILED neither
     * condition held afterwards: `docs` stayed null and `loading` went back to
     * false. `load` is a `useCallback` over `loading`, so flipping it changed
     * the callback's identity, which re-ran the effect that calls `load()`,
     * which fetched again — an unbounded retry loop against the server, at
     * whatever rate the failures came back. A 404 on the index after a bad
     * deploy turned every reader with the dialog open into a fetch loop.
     *
     * Invisible until the failure was instrumented: the dialog just showed
     * "search is unavailable" and the loop ran behind it.
     *
     * Cleared when the dialog closes (see the `open` effect), so reopening is
     * a deliberate second attempt — which is the retry a reader would expect
     * and the only one they get.
     */
    const attempted = useRef(false)

    const load = useCallback(async () => {
        if (docs || loading || attempted.current) return

        attempted.current = true

        setLoading(true)
        setFailed(false)

        try {
            const res = await fetch(indexUrl)
            if (!res.ok) throw new Error(String(res.status))
            const json = (await res.json()) as { docs: Doc[] }
            setDocs(json.docs)
        } catch (e) {
            setFailed(true)

            /*
             * The index is a static file fetched on first keystroke. When a bad
             * deploy leaves it 404ing, search quietly stops working and nothing
             * server-side records a failure the reader experienced.
             */
            track('docs_search_error', {
                url: indexUrl,
                reason: e instanceof Error ? e.message : 'unknown',
            })
        } finally {
            setLoading(false)
        }
    }, [docs, loading, indexUrl])

    /*
     * The open event, in an effect keyed on `open` ALONE.
     *
     * It cannot live in the effect below that calls `load()`: `load` is a
     * `useCallback` over `docs` and `loading`, both of which change while the
     * dialog is up, so that effect re-runs several times per open — and the
     * first version of this fired six `docs_search_open` rows for one press
     * of `/`. Measured, not reasoned about.
     *
     * Its own effect rather than a call beside each `setOpen(true)` because
     * there are three of those: the button, ⌘K and `/`.
     */
    useEffect(() => {
        if (open) track('docs_search_open')
    }, [open])

    // ⌘K / Ctrl+K from anywhere, and `/` when not already typing somewhere.
    const id = useRef(Symbol('docs-search'))

    useEffect(() => {
        // First one mounted claims it; see `shortcutOwner` above.
        if (shortcutOwner === null) shortcutOwner = id.current
        if (shortcutOwner !== id.current) return

        const onKey = (e: KeyboardEvent) => {
            const inField =
                e.target instanceof HTMLElement &&
                (e.target.tagName === 'INPUT' ||
                    e.target.tagName === 'TEXTAREA' ||
                    e.target.isContentEditable)

            if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'k') {
                e.preventDefault()
                setOpen((v) => !v)
                return
            }

            if (e.key === '/' && !inField && !open) {
                e.preventDefault()
                setOpen(true)
            }
        }

        window.addEventListener('keydown', onKey)

        return () => {
            window.removeEventListener('keydown', onKey)

            // Hand the claim back, so a remount does not leave the shortcut
            // owned by an instance that no longer exists.
            if (shortcutOwner === id.current) shortcutOwner = null
        }
    }, [open])

    useEffect(() => {
        if (!open) {
            /*
             * Closing. Report an abandonment only when a query was actually
             * searched and nothing was opened from it — a reader who pressed
             * escape on an empty box did not fail to find anything.
             */
            if (searched.current && !picked.current)
                track('docs_search_abandon', {
                    query: queryField(lastQuery.current),
                    results: hitsRef.current,
                })

            searched.current = false
            picked.current = false
            lastQuery.current = ''

            // One index attempt per open — see `attempted` above.
            attempted.current = false

            return
        }

        void load()
        // The dialog owns the page while it is up; restoring scroll on close is
        // handled by simply removing the class again.
        document.documentElement.classList.add('overflow-hidden')
        const id = window.setTimeout(() => inputRef.current?.focus(), 10)

        return () => {
            document.documentElement.classList.remove('overflow-hidden')
            window.clearTimeout(id)
        }
    }, [open, load])

    const hits = useMemo(
        () => (docs ? search(docs, query) : []),
        [docs, query]
    )

    /*
     * The current hit count, readable from the close handler above without
     * making it depend on `hits` — that dependency would tear the effect down
     * and rebuild it on every keystroke.
     */
    const hitsRef = useRef(0)
    hitsRef.current = hits.length

    /*
     * One event per SETTLED query, not per keystroke.
     *
     * Typing "authentication" fires `onChange` fourteen times, and thirteen of
     * those are prefixes nobody searched for — filing them would bury the real
     * query under its own substrings and make "what do people look for"
     * unanswerable. 500ms after the last keystroke is a pause; anything
     * shorter files "auth" on the way to "authentication".
     *
     * `results: 0` is the row worth having: a reader asking the documentation
     * a question it does not answer, in their own words.
     */
    useEffect(() => {
        if (!open || !docs) return

        const q = query.trim()

        if (q.length < 2 || q === lastQuery.current) return

        const id = window.setTimeout(() => {
            lastQuery.current = q
            searched.current = true

            track('docs_search_query', {
                query: queryField(q),
                results: hitsRef.current,
            })
        }, 500)

        return () => window.clearTimeout(id)
    }, [open, docs, query, hits.length])

    useEffect(() => setCursor(0), [query])

    /**
     * A result was chosen — by click or by Enter.
     *
     * `rank` is the only feedback the scoring in `lib/search.ts` ever gets: a
     * corpus where the answer is habitually fourth is a corpus whose scoring
     * is wrong, and nothing else would say so.
     */
    const onPick = (href: string, rank: number, via: 'enter' | 'click') => {
        picked.current = true

        track('docs_search_select', {
            query: queryField(query),
            href,
            rank: rank + 1,
            results: hits.length,
            via,
        })
    }

    const onKeyDown = (e: React.KeyboardEvent) => {
        if (e.key === 'Escape') {
            e.preventDefault()
            setOpen(false)
            return
        }

        if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
            e.preventDefault()
            setCursor((c) => {
                const next = e.key === 'ArrowDown' ? c + 1 : c - 1
                if (hits.length === 0) return 0
                return (next + hits.length) % hits.length
            })
            return
        }

        if (e.key === 'Enter') {
            const hit = hits[cursor]
            if (hit) {
                e.preventDefault()
                onPick(hit.doc.href, cursor, 'enter')
                window.location.href = hit.doc.href
            }
        }
    }

    // Keep the highlighted row in view as the arrows walk past the fold.
    useEffect(() => {
        const el = listRef.current?.children[cursor] as HTMLElement | undefined
        el?.scrollIntoView({ block: 'nearest' })
    }, [cursor])

    return (
        <>
            <button
                type="button"
                onClick={() => setOpen(true)}
                onMouseEnter={() => void load()}
                className={`group flex w-full items-center gap-2 rounded-lg border border-border bg-surface-secondary px-2.5 py-1.5 text-left text-sm text-muted transition-colors hover:border-accent/40 hover:text-foreground ${className}`}
            >
                <Search className="h-4 w-4 shrink-0" />
                <span className="min-w-0 flex-1 truncate">
                    {t('docs.search.placeholder')}
                </span>
                <kbd className="hidden shrink-0 rounded border border-border bg-surface px-1.5 py-px font-mono text-[0.6875rem] text-muted @xs:inline">
                    {shortcutHint()}
                </kbd>
            </button>

            {/*
                Portalled to <body> for the same reason the docs drawer is:
                <main> is a stacking context (`relative z-20` in Layout.astro),
                so a `fixed` overlay rendered inside it cannot rise above the
                shared <Header/> at `z-40`, whatever z-index it asks for.
            */}
            {open && createPortal(
                <div
                    className="fixed inset-0 z-[100] flex items-start justify-center overflow-y-auto p-4 pt-[10vh]"
                    role="dialog"
                    aria-modal="true"
                    aria-label={t('docs.search.title')}
                >
                    <button
                        type="button"
                        aria-label={t('docs.search.close')}
                        onClick={() => setOpen(false)}
                        className="fixed inset-0 cursor-default bg-black/60 backdrop-blur-sm"
                    />

                    <div className="relative w-full max-w-2xl overflow-hidden rounded-2xl border border-border bg-surface shadow-2xl">
                        <div className="flex items-center gap-2 border-b border-border px-4">
                            <Search className="h-4 w-4 shrink-0 text-muted" />
                            <input
                                ref={inputRef}
                                value={query}
                                onChange={(e) => setQuery(e.target.value)}
                                onKeyDown={onKeyDown}
                                type="search"
                                autoComplete="off"
                                spellCheck={false}
                                placeholder={t('docs.search.placeholder')}
                                aria-label={t('docs.search.placeholder')}
                                className="min-w-0 flex-1 bg-transparent py-3.5 text-foreground outline-none placeholder:text-muted"
                            />
                            <button
                                type="button"
                                onClick={() => setOpen(false)}
                                aria-label={t('docs.search.close')}
                                className="rounded p-1 text-muted transition-colors hover:bg-surface-hover hover:text-foreground"
                            >
                                <X className="h-4 w-4" />
                            </button>
                        </div>

                        <div className="max-h-[60vh] overflow-y-auto">
                            {failed ? (
                                <p className="px-4 py-8 text-center text-sm text-muted">
                                    {t('docs.search.failed')}
                                </p>
                            ) : loading && !docs ? (
                                <p className="px-4 py-8 text-center text-sm text-muted">
                                    {t('docs.search.loading')}
                                </p>
                            ) : query.trim().length === 0 ? (
                                <p className="px-4 py-8 text-center text-sm text-muted">
                                    {t('docs.search.hint')}
                                </p>
                            ) : hits.length === 0 ? (
                                <p className="px-4 py-8 text-center text-sm text-muted">
                                    {t('docs.search.empty', { query })}
                                </p>
                            ) : (
                                <ul ref={listRef} className="p-2">
                                    {hits.map((hit, i) => (
                                        <li key={hit.doc.path}>
                                            <a
                                                href={hit.doc.href}
                                                onClick={() =>
                                                    onPick(hit.doc.href, i, 'click')
                                                }
                                                onMouseEnter={() => setCursor(i)}
                                                className={`block rounded-lg px-3 py-2.5 transition-colors ${
                                                    i === cursor
                                                        ? 'bg-accent/12'
                                                        : 'hover:bg-surface-secondary'
                                                }`}
                                            >
                                                <div className="flex items-center gap-2">
                                                    <FileText className="h-3.5 w-3.5 shrink-0 text-muted" />
                                                    <span className="truncate text-xs text-muted">
                                                        {hit.doc.sectionTitle}
                                                    </span>
                                                </div>
                                                <div className="mt-0.5 font-pjs text-sm font-semibold text-foreground">
                                                    {hit.doc.title}
                                                </div>
                                                <p
                                                    className="mt-0.5 line-clamp-2 text-xs text-muted [&_mark]:bg-transparent [&_mark]:font-semibold [&_mark]:text-accent"
                                                    dangerouslySetInnerHTML={{
                                                        __html: hit.snippet,
                                                    }}
                                                />
                                            </a>
                                        </li>
                                    ))}
                                </ul>
                            )}
                        </div>

                        <div className="flex items-center gap-4 border-t border-border px-4 py-2 text-[0.6875rem] text-muted">
                            <span className="flex items-center gap-1">
                                <CornerDownLeft className="h-3 w-3" />
                                {t('docs.search.keyOpen')}
                            </span>
                            <span>↑↓ {t('docs.search.keyMove')}</span>
                            <span>esc {t('docs.search.keyClose')}</span>
                        </div>
                    </div>
                </div>,
                document.body
            )}
        </>
    )
}

/** ⌘K on Apple keyboards, Ctrl K everywhere else. */
function shortcutHint(): string {
    if (typeof navigator === 'undefined') return 'Ctrl K'
    return /Mac|iPhone|iPad/.test(navigator.platform || navigator.userAgent)
        ? '⌘ K'
        : 'Ctrl K'
}
